"""Generate unicode_tables.inc for the native Qwen2 tokenizer (NFC + the \\p{L} / \\p{N} / \\s classes of its regex).

    python tools/gen_unicode_tables.py > unicode_tables.inc

Data comes from Python's unicodedata; the version is recorded in the output. Hangul syllables are handled
algorithmically in the C++ code and are excluded from the decomposition/composition tables.
"""
import sys, unicodedata as ud

MAX = 0x110000
HANGUL = range(0xAC00, 0xAC00 + 11172)

def ranges(pred):
    out, start = [], None
    for cp in range(MAX + 1):
        ok = cp < MAX and pred(cp)
        if ok and start is None: start = cp
        if not ok and start is not None: out.append((start, cp - 1)); start = None
    return out

cat = lambda cp: ud.category(chr(cp))
letters = ranges(lambda cp: cat(cp) in ('Lu', 'Ll', 'Lt', 'Lm', 'Lo'))
numbers = ranges(lambda cp: cat(cp) in ('Nd', 'Nl', 'No'))
# White_Space property (the \s of Oniguruma / Rust regex in Unicode mode); unicodedata has no direct accessor.
white = [0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x20, 0x85, 0xA0, 0x1680] + list(range(0x2000, 0x200B)) + [0x2028, 0x2029, 0x202F, 0x205F, 0x3000]
ccc = [(cp, ud.combining(chr(cp))) for cp in range(MAX) if ud.combining(chr(cp))]
decomp, comp = [], []
for cp in range(MAX):
    if cp in HANGUL or 0xD800 <= cp < 0xE000: continue
    d = ud.decomposition(chr(cp))
    if not d or d.startswith('<'): continue
    full = [ord(ch) for ch in ud.normalize('NFD', chr(cp))]
    if full != [cp]: decomp.append((cp, full))
    parts = [int(x, 16) for x in d.split()]
    if len(parts) == 2 and ud.normalize('NFC', ud.normalize('NFD', chr(cp))) == chr(cp):
        comp.append((parts[0], parts[1], cp))
assert max(len(f) for _, f in decomp) <= 4

w = sys.stdout.write
w(f'// Generated by tools/gen_unicode_tables.py from Python unicodedata {ud.unidata_version}. Do not edit.\n')
w(f'static const char *UNICODE_VERSION = "{ud.unidata_version}";\n')
def emit_ranges(name, rs):
    w(f'static const uint32_t {name}[][2] = {{\n')
    for i in range(0, len(rs), 6): w('    ' + ' '.join(f'{{0x{a:X}, 0x{b:X}}},' for a, b in rs[i:i + 6]) + '\n')
    w('};\n')
emit_ranges('UC_LETTER', letters); emit_ranges('UC_NUMBER', numbers)
w('static const uint32_t UC_WHITE[] = {' + ', '.join(f'0x{c:X}' for c in white) + '};\n')
w('static const uint32_t UC_CCC[][2] = {\n')
for i in range(0, len(ccc), 8): w('    ' + ' '.join(f'{{0x{a:X}, {b}}},' for a, b in ccc[i:i + 8]) + '\n')
w('};\n')
w('static const uint32_t UC_DECOMP[][5] = {  // code point, full canonical decomposition (0-terminated)\n')
for i in range(0, len(decomp), 4):
    w('    ' + ' '.join('{' + ', '.join(f'0x{x:X}' for x in [cp] + f + [0] * (4 - len(f))) + '},' for cp, f in decomp[i:i + 4]) + '\n')
w('};\n')
w('static const uint32_t UC_COMP[][3] = {  // first, second, primary composite\n')
for i in range(0, len(comp), 4): w('    ' + ' '.join(f'{{0x{a:X}, 0x{b:X}, 0x{c:X}}},' for a, b, c in comp[i:i + 4]) + '\n')
w('};\n')
print(f'// letters {len(letters)} ranges, numbers {len(numbers)}, ccc {len(ccc)}, decomp {len(decomp)}, comp {len(comp)}', file=sys.stderr)
